name: CI-CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm install

      - run: npm run lint
      - run: npm test -- --watchAll=false

  build:
    needs: test
    runs-on: ubuntu-latest
#    env:
#      - DISABLE_ESLINT_PLUGIN: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm install
      - run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build


  deploy-github-pages:
    needs: build
    runs-on: ubuntu-latest
  
    permissions:
      contents: write   # allows pushing to gh-pages branch
      pages: write      # allows publishing to Pages
      id-token: write
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build
  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

