name: CI-CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm install

      - run: npm run lint
      - run: npm test -- --watchAll=false

  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      PUBLIC_URL: /cicd-react-demo
#     DISABLE_ESLINT_PLUGIN: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm install
      - run: PUBLIC_URL=/cicd-react-demo npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build

  
  deploy-github-pages:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
  
    permissions:
      pages: write
      id-token: write
  
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build
  
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build   # uploads the contents of build/
  
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4

